# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Combo < Formula
  desc ""
  homepage "https://github.com/tolgaOzen/combo"
  version "0.1.7"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    url "https://github.com/tolgaOzen/combo/releases/download/v0.1.7/combo_0.1.7_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "cd5f5aff25b01556615ad25c1ae9a50a74c027b015857223dc6de3cbbb8f4899"

    def install
      bin.install "combo"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tolgaOzen/combo/releases/download/v0.1.7/combo_0.1.7_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "d60d37fda6da39b2ec23c8d96cafb781da5298346f11f6b3cfc2d37967d21737"

        def install
          bin.install "combo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tolgaOzen/combo/releases/download/v0.1.7/combo_0.1.7_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "e5440a2c5a5c35f4d01cc06d15d18366186ca5ac1520786fd22e4460c319acce"

        def install
          bin.install "combo"
        end
      end
    end
  end
end
