# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Combo < Formula
  desc ""
  homepage "https://github.com/tolgaOzen/combo"
  version "0.1.6"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    url "https://github.com/tolgaOzen/combo/releases/download/v0.1.6/combo_0.1.6_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "e75046b7d9720aa89fb6094b75ba816a34ec4a30a5b69910be855c056c019a0a"

    def install
      bin.install "combo"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tolgaOzen/combo/releases/download/v0.1.6/combo_0.1.6_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "a640b0f37435a499648419391d4998fe687c2182b12d15ad2781fce2c8adc52a"

        def install
          bin.install "combo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tolgaOzen/combo/releases/download/v0.1.6/combo_0.1.6_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "1c1b5cfbe46c02f32581512555b40d07af42b9d2176bb0d106440ca2409588d9"

        def install
          bin.install "combo"
        end
      end
    end
  end
end
