# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Combo < Formula
  desc ""
  homepage "https://github.com/tolgaOzen/combo"
  version "0.2.3"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    url "https://github.com/tolgaOzen/combo/releases/download/v0.2.3/combo_0.2.3_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "d33044de2bd99a35c6c1f645809618ff5667f84c2509719f13f1cb1a85938cfc"

    def install
      bin.install "combo"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tolgaOzen/combo/releases/download/v0.2.3/combo_0.2.3_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "dd8762ab077b5989629862f7f584f90866204c79f502a31dd87b7140922cba84"

        def install
          bin.install "combo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tolgaOzen/combo/releases/download/v0.2.3/combo_0.2.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "b677c0d528a1b538e106f2027b045dce568ca219ee0a89db9d3a0c8e9f268be4"

        def install
          bin.install "combo"
        end
      end
    end
  end
end
